### ISSUE TITLE
Adapt Microservice architecture

### ISSUE THREAD

**Issue by olikami** [Chreggii/syntax-highlighter#72]
- Public API makes 3 calls
   - call Formal model Highlighting
   - call ML predict
   - async call ML train
- ML predict requests Formal Syntax Highlighter as needed
  - call lexing endpoint for predit
  - call highlight endpoint for training

**ToDo**:
- [x] Adapt sequence diagram @olikami #74
- [x] Adapt architecture diagram @olikami #75
- [x] Adapt ML API specs @olikami #76 
- [x] Adapt Public API calls @Chreggii 

Also needs to be accounted for in #15  @epura @alainkueng
